version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    # container_name: db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    # container_name: backend
    image: jischin/taski_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
  frontend:
    # container_name: frontend
    image: jischin/taski_frontend  # Качаем с Docker Hub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    # container_name: gateway
    image: jischin/taski_gateway  # Качаем с Docker Hub
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80
